== Einordnung in historische und aktuelle Forschungsthemen <einleitung_historische_aktuelle_Forschungsthemen>
In @einleitung wurde bereits angedeutet, dass das Binärsystem und die Berechnung der Gleitkommazahlen zur Basis 2 ein für fast jeden geltender Grundsatz der Rechnerarchitektur in gewisser Weise hinterfragt werden soll. Die Forschungsfrage und das Thema der Masterarbeit mag dabei auf den ersten Blick möglicherweise als "Spielerei" abgetan werden, jedoch wird in diesem Abschnitt sowohl die historische Relevanz der Fragestellung, als auch eine mögliche zukünftige Relevanz der Thematik für moderne Anwendungen (KI, Quantencomputer, etc.) aufgezeigt. Im folgenden Abschnitt wird ein kurzer Überblick über die historische Entwicklung des Binärsystems und der Zahlendarstellung zur Basis 2 gegeben, um den Kontext des Forschungsthemas zu verdeutlichen und auch zu zeigen, wie sich diese Standards entwickelt hatten. Im Weiteren wird auf aktuelle Forschungsthemen, wie Neuronale Netze und Quantencomputer eingegangen, um auch hier die nicht zu vernachlässigende Relevanz des Themas zu zeigen.

=== Historische Entwicklung
Aus dem Thema dieses Abschnittes könnte man problemlos eine komplette Masterarbeit gestalten. Hier soll aber nur ein kleiner Überblick, mit dem Ziel das Binärsystem und die Zahlendarstellung zur Basis 2 zu beleuchten, gegeben werden.
Neben antiken Modellen wird die Vorreiterrolle mit der mathematische Entwicklung des Dualsystems, im 17. Jhdt., wie wir es heute kennen, und die Entwicklung der ersten binären Rechenmaschine Gottfried Wilhelm Leibniz zugesprochen. Dabei wurde das Dualsystem aber lediglich für die Darstellung von Ganzzahlen verwendet. Im 19. Jahrhundert folgten erste Versuche, das binäre System für die Übertragung von Informationen zu nutzen. So wurden beispielsweise in der Telegrafie binäre Codes eingesetzt, um Nachrichten zu verschlüsseln. Der englische Mathematiker George Boole legte mit seiner Booleschen Algebra in @lit_Boole_analysis_of_logic 1847 die Grundlage für die digitale Logik. Seine Arbeit zeigte, wie sich logische Operationen mit Hilfe von binären Werten (0 und 1) darstellen lassen.
Der deutsche Ingenieur Konrad Zuse entwickelte in den 1930er Jahren den ersten programmierbaren Computer, den Z1. Dieser Computer arbeitete bereits mit dem binären Zahlensystem, war aber rein mechanisch konstruiert. Aufbauend auf der Arbeit von Konrad Zuse konnte John von Neumann die heute als von-Neumann-Architektur um ca. 1940 entwickeln. Der ungarisch-amerikanische Mathematiker John von Neumann prägte mit seiner in @lit_von-Neumann_First_Draft_of_a_Report_on_the_EDVAC ,für ENIAC (Electronic Numerical Integrator and Computer), beschriebene Architektur für Computer die Grundlage für die heutige Computerarchitektur. Sowohl Zuses Z3 als auch der ENIAC konnten mit speziell entwickelten mathematischen Modellen Gleitkommazahlen berechnen. 
Der Z3 wurde mit elektromechanischen Relais, der ENIAC mit Elektronenröhren realisiert. Sowohl bei den vorher aufwändig konstruierten, rein mechanisch-arbeitenden Maschinen (Z1) als auch bei den mit Relais und Elektronenröhren umgesetzen Schaltungen war lediglich eine Verwendung des Binärsystems möglich. Für die mechanischen Anlagen waren zur Umsetzung mit dem Binärsystem nur zwei Endanschläge, ohne Zwischenstellungen, nötig, für Relais existieren nur die Stellungen "geschlossen" (1) und "offen" (0). Elektronenröhren wurden ähnlich wie Relais als an/aus-Schalter eingesetzt. Ende der 1950er Jahre wurden die Elektronenröhren durch Transistoren ersetzt. Mit Transistoren wäre die Verwendung von Alternativen zum Binärsystem grundsätzlich möglich, wurde aber wegen der höhreren Fehleranfälligkeit durch Rauschen und vermutlich den bereits verbreiteten Standard der Vorgängermodelle nur beim "Setun" durch die UdSSR versucht @lit_Campbell_The_Setun_Computer. Der Setun blieb bisher der einzige Computer, der auf dem Ternärsystem basiert und lief laut den Entwicklern meist fehlerfrei. \
Gleitkommazahlen wurden anfangs bei jedem Computermodell mit unterschiedlichen Berechnungsmodellen berechnet, weswegen in den 1980er Jahren der Standard IEEE 754 für Gleitkommazahlen (@einleitung_zahlendarstellung_in_der_informatik) eingeführt wurde und die Computerindustrie vereinheitlichte @lit_ORegan_a_brief_history_of_computing.

=== Binärsystem und Zahlendarstellung zur Basis 2
Das Binärsystem ermöglicht es, ohne großen Aufwand logische Operationen durchzuführen und Informationen in elektrischen Schaltkreisen zu speichern und zu verarbeiten. 
Die Darstellung im Binärsystem mit lediglich 0 und 1 und damit auch die Zahlendarstellung zur Basis 2 ist aber in erster Linie auf die Einfachheit der Umsetzung mit Schaltkreisen, Relais und später der niedrigen Störanfälligkeit von Transistoren zurückzuführen @lit_ottoSpaniol_arithmetik_in_rechenanlagen.

Nichtsdestotrotz ist das Binärsystem aber nicht in Stein gemeißelt, wie bereits zu Beginn in @einleitung mit Otto Spaniols Überlegung in @lit_ottoSpaniol_arithmetik_in_rechenanlagen zu alternativen Modellen, gezeigt wurde. 

Setun Computer mit dem Ternärsystem $[-1;0;1]$ 

BCD-System

#text(red)[BCD und Ternärsystem]

#text(red)[#lorem(50)]

=== Aktuelle Forschungsthemen
Computer sind aus unserem Alltag nicht mehr wegzudenken. Sie steuern Autos, Flugzeuge, medizinische Geräte und vieles mehr. Das Internet verbindet Menschen weltweit und ermöglicht den Zugriff auf eine unendliche Menge an Informationen. Die Entwicklung des Computers hat unser Leben grundlegend verändert und wird es mit zufünftigen Entwicklungen weiterhin verändern. Fortschritte und neue Problemstellungen bei der Entwicklung von Quantencomputern, Künstlicher Intelligenz, Neuronalen Netzen oder auch neue Fertigungstechnologien und Materialien können sich auf die Rechnerarchitektur und das verwendete System zur Zahlendarstellung nehmen. \
Im Weiteren soll auf Künstliche Intelligenz bzw. Neuronale Netze und Quantencomputer eingegangen werden, da hier die Relevanz des Forschungsthemas mit aktuellem Bezug verdeutlicht werden kann.

==== Künstliche Intelligenz und Neuronale Netze
Neuronale Netze sind eine Art von Algorithmus, der aus miteinander verbundenen Knoten (Neuronen) besteht. Diese Knoten verarbeiten Informationen und leiten sie an nachfolgende Knoten weiter. Die Verbindungen zwischen den Knoten haben Gewichte, die während des Lernprozesses angepasst werden.

//===== Binärsystem
Die Berechnungen in neuronalen Netzen werden in der Regel durch herkömmliche Gleitkommazahlen (Double) mit dem Wertebereich $[0;1]$ umgesetzt. Kurzgefasst und vereinfacht hat jeder Knoten in einem neuronalen Netz eine Aktivierungsfunktion und eine gewichtete Summe aus dem sich der Wert des Knotens, den er an die nächsten Knoten weiterleitet, berechnet. Die Berechnung in neuronalen Netzen findet also in erster Linie mit Gleitkommazahlen statt #text(red)[Quelle? Skript ML?]. Die dadurch entstehenden Einschränkungen und die ungleiche Verteilung wird in @einleitung_zahlendarstellung_in_der_informatik und @einleitung_zahlendarstellung_für_die_logistische_abbildung dargestellt. 

Alternativ gibt es aber in der aktuellen Forschung auch rein binäre neuronale Netze, die eine vielversprechende Alternative zu traditionellen neuronalen Netzen, insbesondere für Anwendungen, bei denen Energieeffizienz und Geschwindigkeit im Vordergrund stehen, bieten #text(red)[Quelle?].

//===== Alternativen zum Binärsystem
Als gewinnbringende Alternative zum Binärsystem kann das Ternärsystem angeführt werden. Einige biologische Prozesse scheinen auf ternären (oder multivalenten) Zuständen zu beruhen. Dadurch könnte die Verwendung des Ternärsystems (oder eines multivalenten Systems) die Prozesse der biologischen neuronalen Netze besser nachbilden. #text(red)[Quelle?]
Zusätzlich bietet das Ternärsystem (0, 1 und -1) im Vergleich zum binären System (0 und 1) eine Granularität, die bei der Darstellung von Informationen helfen kann. Dies könnte zu effizienteren Berechnungen mit reduzierter Komplexität führen. #text(red)[Quelle?]
Des Weiteren könnten ternäre Neuronennetze weniger Energie verbrauchen, da sie weniger Berechnungen erfordern und weniger Speicherplatz benötigen. #text(red)[Quelle?]

//===== Zusammenfassung
Aktuelle KI Implementierungen und neuronale Netze benötigen noch Optimierungen um noch näher an den realen menschlichen Denkprozess heranzukommen. Dafür ist möglicherweise eine andere Rechnerarchitektur und eventuell ein anderes Zahlensystem günstig oder gar notwendig. Wie in den vorhergehenden Abschnitt beschrieben, bietet das Ternärsystem Potenzial für die Entwicklung effizienter und energieeffizienter neuronaler Netze.

Abgesehen von den rein binären, ternären oder anders-Basigen neuronalen Netzen kann hier noch ein weiterer Bezug zum Thema dieser Arbeit hergestellt werden. Für die Verwendung von Gleitkommazahlendarstellung in Neuronalen Netzen können möglicherweise auch bessere Modelle als die aktuell verwendeten (@einleitung_zahlendarstellung_in_der_informatik) entworfen werden. Ein Modell, dass den benötigten Zahlenbereich von $[0;1]$ oder auch $[-1;0;1]$ gleichmäßiger und somit ggf. besser abbilden kann, könnte Vorteile aufweisen #text(red)[Quelle?].

==== Quantencomputer
Während klassische Computer auf der Grundlage des binären Zahlensystems operieren, das Informationen in Form von Bits codiert, die entweder den Zustand 0 oder 1 annehmen, nutzen Quantencomputer das Prinzip der Quantenüberlagerung und -verschränkung. Qubits, die Quanteneinheit der Information, können sich in einer Superposition mehrerer Zustände gleichzeitig befinden. Das heißt, dass der Wert eines Bits mit einer bestimmten Wahrscheinlichkeit 0 bzw. 1 annimmt.

//===== Qubits
Obwohl Qubits über die Fähigkeiten klassischer Bits hinausgehen, müssen sie als Verallgemeinerung betrachtet werden. Ein klassischer Bit ist aus der Sichtweise der Quantencomputerforschung nur ein Spezialfall eines Qubits, bei dem die Wahrscheinlichkeitsamplitude für einen der beiden Zustände Null ist. \ Auf den ersten Blick mag es nun widersprüchlich erscheinen, von Quantencomputern zu sprechen, die auf dem binären System basieren. Quantencomputer nutzen schließlich Qubits, die im Gegensatz zu klassischen Bits nicht nur den Zustand 0 oder 1 annehmen können, sondern sich in einer Überlagerung beider Zustände befinden. Trotz der scheinbaren Diskrepanz ist das binäre System auch hier die Grundlage aller digitalen Berechnungen. Obwohl die Berechnungen innerhalb eines Quantencomputers auf der Grundlage von Quantenmechanik und Überlagerung erfolgen, sind die Ergebnisse, die wir letztendlich ablesen, binär. Quantenalgorithmen sind so konzipiert, dass sie die Wahrscheinlichkeitsamplituden der Qubits so manipulieren, dass die Messung mit hoher Wahrscheinlichkeit das gewünschte Ergebnis liefert. Diese Eigenschaft ermöglicht es Quantencomputern, bestimmte Probleme, wie beispielsweise die Faktorisierung großer Zahlen oder die Simulation von Quantensystemen, exponentiell schneller zu lösen als klassische Computer.

//===== Relevanz des klassischen Binärsystems mit "normalen" Bit
Unabhängig von zukünftigen Berechnungsmöglichkeiten von Quantencomputern mit Qubit und der Verbreitung von Quantencomputern, ist anzunehmen, dass "normale" Bit die Schnittstelle zur klassischen Computerwelt bleiben, da Quantencomputer vermutlich auch mit herkömmlichen Computern interagieren müssen. Zudem erfolgt die Eingabe und Ausgabe von Daten mit hoher Wahrscheinlichkeit weiterhin in binärer Form.

//===== Alternativen zum Binärsystem
Das Ternärsystem (mit den Zuständen 0, 1 und 2) und weitere Systeme sind theoretisch möglich und bietet den Vorteil, dass mit nur einem Bit noch mehr Möglichkeiten in einer Berechnung abgebildet werden (höhere Informationsdichte) und somit die Effizienz und die Geschwindigkeit erhöht werden kann. Die physikalische Realisierung von Qubits, die mehr als zwei Zustände zuverlässig darstellen können, ist wie bei normalen Bits, technisch anspruchsvoll. Fehlerkorrekturcodes, die für binäre Systeme entwickelt wurden, müssten für ternäre Systeme angepasst werden. Zudem sind Quantenalgorithmen in der Regel für binäre Qubits konzipiert. Eine Erweiterung auf ternäre Systeme würde neue Algorithmen und theoretische Grundlagen erfordern.

//===== Zusammenfassung
Derzeit liegt der Schwerpunkt der Quanteninformatik auf der Entwicklung stabiler und skalierbarer Quantencomputer auf Basis von binären Qubits. Die Erforschung von ternären oder allgemeiner multivalenter Quantenbits ist aktuell noch ein weitgehend unerforscht. Die grundsätzliche Überlegung für diesen Bereich wird aber von Earl Campbell in @lit_Campbell_The_Setun_Computer erwähnt.
Für weitere Abschätzungen der Sinnhaftigkeit des Forschungsthemas ist dazu aber zunächst die physikalische Realisierbarkeit zu untersuchen. Des Weiteren müssen zunächst auch Probleme identifiziert werden, bei denen multivalente Quantencomputer entscheidende Vorteile bieten und überdies müssen dann  Quantenalgorithmen entwickelt werden, die die Vorteile von multivalenten Qubits auch nutzen.

==== Zusammenhang Forschungsfrage und zukünftige Entwicklung
In diesem Abschnitt sollte ein Überblick geschaffen werden, warum das Thema dieser Arbeit sowohl historisch als auch zukünfig für hochmoderne Anwendungen (z.B. Neuronale Netze und Quantencomputer) interessant war und sein wird und dass die Verwendung von alternativen Zahlensystemen nach Stand der aktuellen Forschung unter Umständen neue Wege für energieeffizientere und leistungsfähigere Computer eröffnen könnte.
Zudem können Fortschritte im Bereich der Forschung an den beschriebenen Themen zu vollkommen neuen, heute noch nicht absehbaren oder denkbaren, Anforderungen an die Rechnerarchitektur führen. Ob aber dadurch auf die Verwendung des Binärsystems, und damit die Basis 2 für die Berechnung der Zahlendarstellungen, für die Rechner der Zukunft verzichtet wird, muss sich noch herausstellen.


